name: lpt-application-ui CI

on: [push]

permissions:
  actions: read
  contents: read

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Eco-CI Init
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'repo checkout'
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Npm Cache Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'cache npm dependencies'
      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit --no-progress --no-fund
      - name: Install Dependencies Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'install dependencies'
#      - name: Check linting across the board
#        shell: bash
#        run: npm run lint:ci
#      - name: Lint Measurement
#        uses: green-coding-solutions/eco-ci-energy-estimation@v4
#        with:
#          task: get-measurement
#          label: 'lint app'
#      - name: Build application
#        shell: bash
#        run: npm run build:gcp
#      - name: Build Measurement
#        uses: green-coding-solutions/eco-ci-energy-estimation@v4
#        with:
#          task: get-measurement
#          label: 'build:gcp app'
#      - name: Run unit tests
#        shell: bash
#        run: |
#          # no tests to run:
#          npm run test:cover || echo 0
#      - name: Unit Tests Measurement
#        uses: green-coding-solutions/eco-ci-energy-estimation@v4
#        with:
#          task: get-measurement
#          label: 'unit tests'
      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
