name: lpt-application-ui CI

on: [push]

permissions:
  read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    container: node:22

    steps:
      - name: Install Eco-CI Dependencies
        run: |
          apt-get update
          apt-get install -y jq gawk coreutils
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
        # continue-on-error: true # recommended setting for production. See notes below.
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'repo checkout'
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache dependencies
        uses: actions/cache@v4.0.1
        id: npm-cache
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            /github/home/.cache/Cypress
          key: npm-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cypress-
            npm-
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'cache npm dependencies'
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-progress --no-fund
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'install dependencies'
      - name: Lint application code
        shell: bash
        run: npm run lint
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'lint app'
      - name: Build application
        shell: bash
        run: npm run build
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'build app'
      - name: Run unit tests
        shell: bash
        run: npm run test:unit
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'unit tests'
      - name: Run E2E tests
        shell: bash
        run: npm run test:e2e
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'e2e tests'
      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
