name: lpt-application-ui CI

on: [push]

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Eco-CI Init
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'repo checkout'
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache dependencies
        uses: actions/cache@v4.0.1
        id: npm-cache
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            /github/home/.cache/Cypress
          key: npm-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cypress-
            npm-
      - name: Npm Cache Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'cache npm dependencies'
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-progress --no-fund
      - name: Install Dependencies Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'install dependencies'
#      - name: Check linting across the board
#        shell: bash
#        run: npm run lint:ci
#      - name: Lint Measurement
#        uses: green-coding-solutions/eco-ci-energy-estimation@v4
#        with:
#          task: get-measurement
#          label: 'lint app'
#      - name: Build application
#        shell: bash
#        run: npm run build:gcp
#      - name: Build Measurement
#        uses: green-coding-solutions/eco-ci-energy-estimation@v4
#        with:
#          task: get-measurement
#          label: 'build:gcp app'
#      - name: Run unit tests
#        shell: bash
#        run: |
#          # no tests to run:
#          npm run test:cover || echo 0
#      - name: Unit Tests Measurement
#        uses: green-coding-solutions/eco-ci-energy-estimation@v4
#        with:
#          task: get-measurement
#          label: 'unit tests'
      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
